extends:
  # https://www.conventionalcommits.org/en/v1.0.0/
  # https://commitlint.js.org/reference/configuration.html
  - '@commitlint/config-conventional'
parserPreset:
  issuePrefixes:
    - 'Issue'
rules:
  references-empty: [2, 'never']
  subject-case:
    - 0
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - chore
      - issue
  header-max-length:
    - 0
    - always
    - 10
  body-max-line-length:
    - 0
    - always
    - Infinity
  footer-max-line-length:
    - 0
    - always
    - Infinity
